name: Build & Publish Talos installer

on:
  push:
    branches: [ main ]
    paths:
      - 'extensions.list'
      - '.github/workflows/installer-image.yml'
      - '.github/renovate.json'
  workflow_dispatch:

jobs:
  build-install-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Talos version
        id: talos
        run: echo "version=1.10.5" >> $GITHUB_OUTPUT

      - name: Show chosen Talos version
        run: echo "Building *metal* image for Talos v${{ steps.talos.outputs.version }} (amd64)"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push installer OCI image
        run: |
          TALOS_VER=v${{ steps.talos.outputs.version }}
          ARCHES=amd64
          EXT_ARGS=$(awk '{print " --system-extension-image "$0}' extensions.list | tr -d '\n')

          mkdir -p _out/installer
          docker run --rm --privileged \
            -v /dev:/dev \
            -v "${{ github.workspace }}/_out/installer":/out \
            ghcr.io/siderolabs/imager:${TALOS_VER} \
            --arch ${ARCHES} ${EXT_ARGS} installer

          # Load the tar that imager writes
          docker load -i _out/installer/installer-amd64.tar

          BASE=ghcr.io/siderolabs/installer-base:${TALOS_VER}
          if ! docker image inspect $BASE >/dev/null 2>&1; then
            BASE=ghcr.io/siderolabs/installer:${TALOS_VER}
          fi

          # Tag & push to GHCR
          docker tag $BASE \
                    ghcr.io/${{ github.repository_owner }}/thinktank-talos-installer:${TALOS_VER}
          docker push ghcr.io/${{ github.repository_owner }}/thinktank-talos-installer:${TALOS_VER}

          # (optional) move latest tag
          docker tag ghcr.io/${{ github.repository_owner }}/thinktank-talos-installer:${TALOS_VER} \
                     ghcr.io/${{ github.repository_owner }}/thinktank-talos-installer:latest
          docker push ghcr.io/${{ github.repository_owner }}/thinktank-talos-installer:latest 